
scenario: ""

time: "$HOME/.local/bin/time"
pcaone: "PCAone"
terapca: "TeraPCA"
propca: "propca"
flashpca: "flashpca"
plink1: "plink"
plink2: "plink2"
smartpca: "smartpca"
csv2bin: "$HOME/.julia/packages/OnlinePCA/isnHZ/bin/csv2bin"
sumr: "$HOME/.julia/packages/OnlinePCA/isnHZ/bin/sumr"
jlhalko: "$HOME/.julia/packages/OnlinePCA/isnHZ/bin/halko"
julia: "$HOME/.local/bin/julia"

figure1:
  dataset: ["asian", "1000G"]
  pcs: [2, 5, 10, 20, 30, 40]
  threads: 4
  # pcaone options
  windows: [64]
  pcaonea: "--svd 2 --memory 2"
  pcaonef: "--svd 0 --memory 2 --tol 1e-4 --maxp 40 --printu"
  pcaoneh: "--svd 1 --memory 2 --tol 1e-4 --maxp 40 --printu"
  # other program options
  terapca: "-filewrite 1 -print 2 -memory 2"
  propca: "-vn -cl 0.001 -a"
  flashpca: "--verbose --memory 4100"

figure2:
  dataset: "NA"
  pcs: [20, 40]
  threads: 20
  # pcaone options
  windows: [64]
  pcaonea: "--svd 2 --memory 4"
  pcaonef: "--svd 0 --memory 2 --tol 1e-4 --maxp 40"
  pcaoneh: "--svd 1 --memory 2 --tol 1e-4 --maxp 40"
  # terapca options
  terapca: "-filewrite 1 -print 2 -memory 4"
  propca: "-vn -cl 0.001 -a"
  flashpca: "--verbose --memory 4100"

figure2A:
  dataset: ["datas1", "datas2", "datas3", "datas4", "datas5", "datas6"]
  pcs: [20, 40]
  threads: 20
  # pcaone options
  windows: [64]
  pcaonea: "--svd 2 --memory 4"
  pcaonef: "--svd 0 --memory 2 --tol 1e-4 --maxp 40"
  pcaoneh: "--svd 1 --memory 2 --tol 1e-4 --maxp 40"
  # terapca options
  terapca: "-filewrite 1 -print 2 -memory 4"
  propca: "-vn -cl 0.001 -a"
  flashpca: "--verbose --memory 4100"

figure2B:
  dataset: ["datas7", "datas8", "datas9", "datas10", "datas11", "datas12", "datas13"]
  pcs: [20, 40]
  threads: 20
  # pcaone options
  pcaonea: "--svd 2 --memory 4"
  pcaonef: "--svd 0 --memory 2 --tol 1e-4 --maxp 40"
  pcaoneh: "--svd 1 --memory 2 --tol 1e-4 --maxp 40"
  windows: [64]
  # terapca options
  terapca: "-filewrite 1 -print 2 -memory 4"
  propca: "-vn -cl 0.001 -a"
  flashpca: "--verbose --memory 4100"

figure3:
  dataset: ["ukb"]
  pcs: [40]
  threads: 20
  # pcaone options
  windows: [64]
  pcaonea: "--svd 2 --memory 20"
  pcaonef: "--svd 0 --tol 1e-4 --maxp 20 --memory 20 --printu"
  pcaoneh: "--svd 1 --tol 1e-9 --maxp 17 --memory 20 --printu"
  # other program options
  # terapca: "-filewrite 1 -print 2 -rfetched 2000"
  terapca: "-filewrite 1 -print 2 -rfetched 4000"
  propca: "-vn -cl 0.001 -a"
  flashpca: "--verbose --memory 20000"

figure4:
  dataset: ["brain_v1"]
  pcs: [40]
  threads: 20
  # pcaone options
  windows: [64]
  pcaonea: "--svd 2 --memory 2"
  pcaonef: "--svd 0 --memory 2"
  pcaoneh: "--svd 1 --memory 2"
  # other program options
  terapca: "-filewrite 1 -print 2 -rfetched 4000"
  propca: "-vn -cl 0.001 -a"
  flashpca: "--verbose --memory 20000"

suppl_bfile:
  # dataset: ["1000G_nsnps1000k", "1000G_nsnps250k", "1000G_nsnps500k", "ukb_array_nsamples5k", "ukb_array_nsamples10k"]
  dataset: ["ukb_array_nsamples5k", "ukb_array_nsamples10k", "ukb_array_nsamples20k", "ukb_array_nsamples100k", "ukb_array_nsamples400k"]
  pcs: [10, 20, 30, 40]
  threads: 10
  # pcaone options
  windows: [8, 16, 32, 64, 128, 256]
  pcaonef: "--svd 0 --memory 2 --maxp 40"
  pcaoneh: "--svd 1 --memory 2 --maxp 40"
  pcaonea: "--svd 2 --memory 2"
  # other program options
  terapca: "-filewrite 1 -print 2 -memory 2"
  propca: "-vn -cl 0.001 -a"
  flashpca: "--verbose --memory 40000"

suppl_bgen:
  dataset: ["ukb_array"]
  pcs: [40]
  threads: 20
  # pcaone options
  windows: [64]
  pcaonef: "--svd 0 --memory 2 --maxp 40"
  pcaoneh: "--svd 1 --memory 2 --maxp 40"
  pcaonea: "--svd 2 --memory 2"
  # other program options
  terapca: "-filewrite 1 -print 2 -memory 2"
  propca: "-vn -cl 0.001 -a"
  flashpca: "--verbose --memory 40000"

test_scrnas:
  dataset: ["brain_v1"]
  # dataset: ["brain", "brain_v1", "brainsp","brainsp_v1","pbmc", "pbmc_v1", "pancreas", "pancreas_v1"]
  pcs: [20, 40]
  threads: 20
  # pcaone options
  windows: [4, 8, 16, 32, 64]
  pcaonea: "--arnoldi --memory 4"
  pcaonef: "--tol 1e-4 --maxp 40 --memory 4"
  pcaoneh: "--tol 1e-4 --maxp 40 --memory 4 --halko"
  # other program options
  terapca: "-filewrite 1 -print 2 -memory 2"
  propca: "-vn -cl 0.001 -a"
  flashpca: "--verbose --batch"

test_ukb:
  dataset: ["ukb"]
  pcs: [40]
  threads: 20
  # pcaone options
  windows: [16, 32, 64, 128]
  pcaonea: "--arnoldi --memory 20"
  pcaonef: "--tol 1e-4 --maxp 20 --memory 20 --printu"
  pcaoneh: "--tol 1e-9 --maxp 20 --memory 20 --halko --printu"
  # other program options
  # terapca: "-filewrite 1 -print 2 -rfetched 2000"
  terapca: "-filewrite 1 -print 2 -memory 2"
  propca: "-vn -cl 0.001 -a"
  flashpca: "--verbose --memory 20000"

asian:
  bed: data/asia/THG.sim.bed
  bim: data/asia/THG.sim.bim
  fam: data/asia/THG.sim.fam

1000G:
  bed: data/1000G/all.2504.bed
  bim: data/1000G/all.2504.bim
  fam: data/1000G/all.2504.fam

1000G_nsnps5k:
  bed: data/1000G_subs/nsnps.5000.bed
  bim: data/1000G_subs/nsnps.5000.bim
  fam: data/1000G_subs/nsnps.5000.fam

1000G_nsnps250k:
  bed: data/1000G_subs/nsnps.250000.bed
  bim: data/1000G_subs/nsnps.250000.bim
  fam: data/1000G_subs/nsnps.250000.fam

1000G_nsnps500k:
  bed: data/1000G_subs/nsnps.500000.bed
  bim: data/1000G_subs/nsnps.500000.bim
  fam: data/1000G_subs/nsnps.500000.fam

1000G_nsnps1000k:
  bed: data/1000G_subs/nsnps.1000000.bed
  bim: data/1000G_subs/nsnps.1000000.bim
  fam: data/1000G_subs/nsnps.1000000.fam

HGDP:
  bed: data/HGDP/all.gnomad.genomes.v3.1.2.hgdp_tgp.snp.maf0.01.bed
  bim: data/HGDP/all.gnomad.genomes.v3.1.2.hgdp_tgp.snp.maf0.01.bim
  fam: data/HGDP/all.gnomad.genomes.v3.1.2.hgdp_tgp.snp.maf0.01.fam

ukb:
  bed: data/ukb/merge.maf0.05.bed
  bim: data/ukb/merge.maf0.05.bim
  fam: data/ukb/merge.maf0.05.fam

ukb_array:
  bed: data/ukb_array/ukb_snp_chip.bgen.vars.bed
  bim: data/ukb_array/ukb_snp_chip.bgen.vars.bim
  fam: data/ukb_array/ukb_snp_chip.bgen.vars.fam
  bgen: data/ukb_array/perm.chip.concat.ld.qc.bgen

ukb_array_nsamples5k:
  bed: data/ukb_array_subs/nsamples.5000.bed
  bim: data/ukb_array_subs/nsamples.5000.bim
  fam: data/ukb_array_subs/nsamples.5000.fam

ukb_array_nsamples10k:
  bed: data/ukb_array_subs/nsamples.10000.bed
  bim: data/ukb_array_subs/nsamples.10000.bim
  fam: data/ukb_array_subs/nsamples.10000.fam

ukb_array_nsamples20k:
  bed: data/ukb_array_subs/nsamples.20000.bed
  bim: data/ukb_array_subs/nsamples.20000.bim
  fam: data/ukb_array_subs/nsamples.20000.fam

ukb_array_nsamples100k:
  bed: data/ukb_array_subs/nsamples.100000.bed
  bim: data/ukb_array_subs/nsamples.100000.bim
  fam: data/ukb_array_subs/nsamples.100000.fam

ukb_array_nsamples400k:
  bed: data/ukb_array_subs/nsamples.400000.bed
  bim: data/ukb_array_subs/nsamples.400000.bim
  fam: data/ukb_array_subs/nsamples.400000.fam

datas1:
  bed: data/bySamples/ukb.samples.10000.bed
  bim: data/bySamples/ukb.samples.10000.bim
  fam: data/bySamples/ukb.samples.10000.fam

datas2:
  bed: data/bySamples/ukb.samples.20000.bed
  bim: data/bySamples/ukb.samples.20000.bim
  fam: data/bySamples/ukb.samples.20000.fam

datas3:
  bed: data/bySamples/ukb.samples.40000.bed
  bim: data/bySamples/ukb.samples.40000.bim
  fam: data/bySamples/ukb.samples.40000.fam

datas4:
  bed: data/bySamples/ukb.samples.60000.bed
  bim: data/bySamples/ukb.samples.60000.bim
  fam: data/bySamples/ukb.samples.60000.fam

datas5:
  bed: data/bySamples/ukb.samples.80000.bed
  bim: data/bySamples/ukb.samples.80000.bim
  fam: data/bySamples/ukb.samples.80000.fam

datas6:
  bed: data/bySamples/ukb.samples.100000.bed
  bim: data/bySamples/ukb.samples.100000.bim
  fam: data/bySamples/ukb.samples.100000.fam

datas7:
  bed: data/bySnps/ukb.nsnps.200000.bed
  bim: data/bySnps/ukb.nsnps.200000.bim
  fam: data/bySnps/ukb.nsnps.200000.fam

datas8:
  bed: data/bySnps/ukb.nsnps.400000.bed
  bim: data/bySnps/ukb.nsnps.400000.bim
  fam: data/bySnps/ukb.nsnps.400000.fam

datas9:
  bed: data/bySnps/ukb.nsnps.600000.bed
  bim: data/bySnps/ukb.nsnps.600000.bim
  fam: data/bySnps/ukb.nsnps.600000.fam

datas10:
  bed: data/bySnps/ukb.nsnps.800000.bed
  bim: data/bySnps/ukb.nsnps.800000.bim
  fam: data/bySnps/ukb.nsnps.800000.fam

datas11:
  bed: data/bySnps/ukb.nsnps.1000000.bed
  bim: data/bySnps/ukb.nsnps.1000000.bim
  fam: data/bySnps/ukb.nsnps.1000000.fam

datas12:
  bed: data/bySnps/ukb.nsnps.2000000.bed
  bim: data/bySnps/ukb.nsnps.2000000.bim
  fam: data/bySnps/ukb.nsnps.2000000.fam

datas13:
  bed: data/bySnps/ukb.nsnps.3000000.bed
  bim: data/bySnps/ukb.nsnps.3000000.bim
  fam: data/bySnps/ukb.nsnps.3000000.fam

brain:
  csv: data/brain/Data.c0.zst
  bin: data/brain/Data.zst

brain_v1:
  csv: data/brain/Data.c1.zst
  bin: data/brain/Data.zst

brainsp:
  csv: data/brain_spinacord/Data.c0.zst
  bin: data/brain_spinacord/Data.zst

brainsp_v1:
  csv: data/brain_spinacord/Data.c0.zst
  bin: data/brain_spinacord/Data.zst

pbmc:
  csv: data/pbmcs/Data.c0.zst

pbmc_v1:
  csv: data/pbmcs/Data.c1.zst

pancreas:
  csv: data/pancreas/Data.c0.zst

pancreas_v1:
  csv: data/pancreas/Data.c1.zst
