from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.4.1")


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/downsample.smk"
include: "rules/refpanels.smk"
include: "rules/genotype_likelihood.smk"
include: "rules/beagle.smk"
include: "rules/stitch.smk"
include: "rules/phaseless.smk"


rule all:
    input:
        get_all_results(),
