time: "/usr/bin/time"

genome:
  fasta: /maps/projects/alab/people/rlk420/datahub/ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
  species: human
  build: hg38
  refpanel: config/refpanel.tsv

samples: config/samples.tsv

coverage: [2.0]
# coverage: [0.1, 0.5, 2.0, 4.0]

chroms: ['chr20']

threads: 60

RUN: 'all'

bcftools:
  bq: 20
  mq: 20

phaseless:
  v0: "/home/rlk420/software/phaseless/release/v0.1.9/phaseless"
  v1: "/home/rlk420/software/phaseless/release/v0.2.5/phaseless"
  C: 10
  chunksize: 1000000000
  iters: 40

stitch:
  bin: "STITCH.R"
  method: 'diploid'
  nGen: 100
  buffer: 'NA'
  K: 10

beagle:
  version41: "/home/rlk420/.local/bin/beagle.27Jan18.7e1.jar"

